### ISSUE TITLE
Establish communication between frontend and backend

### ISSUE THREAD

**Issue by shaneferrellwv** [rb-uf/swe-project#15]
Frontend should submit requests to the backend. Backend should provide a response to the frontend.

**Comment by rb-uf** [comment]
Info on HTTP requests (GET, POST, PUT, DELETE, etc):
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods

Info on making HTTP requests with Angular:
https://angular.io/guide/http

**Comment by Emmett-Kogan** [comment]
Both major pieces of the project are fully communicating with each other now, as the frontend not only receives but uses and displays data supplied by the backend.
